package com.smartup24.cms.instance.example.service;

import static com.smartup24.cms.platform.api.entity.field.EntityFields.instant;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.money;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.select;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.sortable;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.text;

import com.smartup24.cms.platform.api.entity.Entity;
import com.smartup24.cms.platform.api.entity.EntityCapability;
import com.smartup24.cms.platform.api.entity.EntityDefinition;
import com.smartup24.cms.platform.api.entity.EntityDefinition.EntityMenu;
import com.smartup24.cms.platform.api.entity.EntityScope;
import com.smartup24.cms.platform.api.entity.field.FieldDefault;
import com.smartup24.cms.platform.api.entity.field.FieldSource.SystemColumn;
import com.smartup24.cms.platform.api.entity.search.EntitySearchSpec;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * The reference list of the cookbook (plan 10/10, item 6.6): products, generated by {@code cms entity new example
 * products} and {@code cms entity add-field} and finished by hand — one declaration, no hooks, no controller and no
 * screen. Every product is seen by whoever holds the right ({@code all()}); the code is given once and kept, unique
 * among the live rows; a product is archived instead of deleted while requests name it, imported from an xlsx file by
 * its code and found by the global search. The requests ({@link ExampleRequestsEntity}) reference it.
 */
@Configuration
public class ExampleProductsEntity {

    /** The entity's code, its form (ADR-0028) and its list's. */
    public static final String CODE = "example.products";

    /** A code: lower-case letters, digits, dashes and underscores. */
    public static final String CODE_PATTERN = "[a-z0-9_-]+";

    public static final List<String> UNITS = List.of("pcs", "kg", "l");

    public static final EntityDefinition DEFINITION = Entity.define(CODE, CODE)
            .table("ex_products", "p")
            // Reference data: every row for whoever holds the right (ADR-0032, 5.1).
            .scope(EntityScope.all())
            .rights(
                    "example",
                    "example.products.rights.form",
                    Map.of(
                            "view", "example.products.rights.view",
                            "create", "example.products.rights.create",
                            "update", "example.products.rights.update",
                            "delete", "example.products.rights.delete",
                            "import", "example.products.rights.import"))
            .menu(new EntityMenu("nav.example_products", "inventory_2", "workspace", 91, "example"))
            .field(text("code", "example.products.col.code")
                    .column("code")
                    .required()
                    .length(1, 64)
                    .matching(CODE_PATTERN)
                    .readonlyOnUpdate()
                    .list(sortable().searchable()))
            .field(text("name", "example.products.col.name")
                    .column("name")
                    .required()
                    .length(1, 255)
                    .list(sortable().searchable()))
            .field(select("unit", "example.products.col.unit", UNITS, "example.products.unit.")
                    .column("unit")
                    .required()
                    .defaultValue(FieldDefault.fixed("pcs"))
                    .list(sortable()))
            .field(money("price", "example.products.col.price", "UZS", "USD")
                    .money("price_amount", "price_currency")
                    .range(BigDecimal.ZERO, null)
                    .list(sortable()))
            .field(instant("modifiedAt", "example.products.col.modified_at")
                    .system(SystemColumn.MODIFIED_AT)
                    .list(sortable().hidden()))
            .section("main", "entity.section.main", "code", "name", "unit", "price")
            .actions("create", "update")
            .archivable()
            .actions("delete")
            .importKey("code")
            .search(EntitySearchSpec.title("name").body("code"))
            .defaultSort("name", Entity.Sort.ASC)
            .capabilities(
                    EntityCapability.SAVED_VIEWS,
                    EntityCapability.EXPORT,
                    EntityCapability.HISTORY,
                    EntityCapability.BULK)
            .build();

    /** Named apart from the bean of this configuration class itself. */
    @Bean
    public EntityDefinition exampleProductsDefinition() {
        return DEFINITION;
    }
}
