package com.smartup24.cms.instance.example.service;

import static com.smartup24.cms.platform.api.entity.field.EntityFields.hidden;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.instant;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.number;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.ref;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.searchable;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.select;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.sortable;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.text;
import static com.smartup24.cms.platform.api.entity.field.EntityFields.textarea;

import com.smartup24.cms.platform.api.entity.Entity;
import com.smartup24.cms.platform.api.entity.EntityCapability;
import com.smartup24.cms.platform.api.entity.EntityDefinition;
import com.smartup24.cms.platform.api.entity.EntityDefinition.EntityMenu;
import com.smartup24.cms.platform.api.entity.EntityScope;
import com.smartup24.cms.platform.api.entity.field.FieldDefault;
import com.smartup24.cms.platform.api.entity.field.FieldSource.SystemColumn;
import com.smartup24.cms.platform.api.entity.field.QueryRef;
import com.smartup24.cms.platform.api.entity.workflow.EntityWorkflow;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * The reference document with statuses of the cookbook (plan 10/10, item 6.6): purchase requests, generated by
 * {@code cms entity new example requests --hooks} and {@code cms entity add-field} and finished by hand. A request
 * names a product of the reference list ({@link ExampleProductsEntity}) and a quantity, and runs the process draft →
 * submitted → approved or rejected (back to draft by {@code recall}) as record actions with a right each. A submitted
 * request keeps its subject, product and quantity; a decided one is only read. Only a holder of {@code approve} writes
 * the resolution (a field right, ADR-0032, 5.2); the hooks ({@link ExampleRequestsHooks}) stamp the moment of the
 * decision. A request that left its draft is neither deleted nor archived: its state locks or is terminal (ADR-0032,
 * 9.2). A request is in the org unit of its author by default (ADR-0013).
 */
@Configuration
public class ExampleRequestsEntity {

    /** The entity's code, its form (ADR-0028) and its list's. */
    public static final String CODE = "example.requests";

    public static final List<String> STATUSES = List.of("draft", "submitted", "approved", "rejected");

    /** The transitions that decide a request: their save stamps {@code decidedAt}. */
    public static final List<String> DECISIONS = List.of("approve", "reject");

    /** The smallest quantity: a thousandth of a unit. */
    private static final BigDecimal THOUSANDTH = new BigDecimal("0.001");

    public static final EntityDefinition DEFINITION = Entity.define(CODE, CODE)
            .table("ex_requests", "r")
            .scope(EntityScope.orgUnit("org_unit_id", "created_by"))
            .rights(
                    "example",
                    "example.requests.rights.form",
                    Map.of(
                            "view", "example.requests.rights.view",
                            "create", "example.requests.rights.create",
                            "update", "example.requests.rights.update",
                            "delete", "example.requests.rights.delete",
                            "submit", "example.requests.rights.submit",
                            "recall", "example.requests.rights.recall",
                            "approve", "example.requests.rights.approve",
                            "reject", "example.requests.rights.reject"))
            .menu(new EntityMenu("nav.example_requests", "approval", "workspace", 92, "example"))
            .field(text("subject", "example.requests.col.subject")
                    .column("subject")
                    .required()
                    .length(1, 255)
                    .list(sortable().searchable()))
            .field(ref("productId", "example.requests.col.product_id")
                    .column("product_id")
                    .target(ExampleProductsEntity.CODE, "name")
                    .required()
                    .list(sortable()))
            .field(number("qty", "example.requests.col.qty")
                    .column("qty")
                    .required()
                    .scale(3)
                    .range(THOUSANDTH, new BigDecimal("1000000"))
                    .list(sortable()))
            .field(select("status", "example.requests.col.status", STATUSES, "example.requests.status.")
                    .column("status")
                    .readonly()
                    .defaultValue(FieldDefault.fixed("draft"))
                    .list(sortable()))
            .field(textarea("resolution", "example.requests.col.resolution")
                    .column("resolution")
                    .length(null, 2000)
                    .readonlyUnless(CODE, "approve")
                    .list(searchable().hidden()))
            .field(instant("decidedAt", "example.requests.col.decided_at")
                    .column("decided_at")
                    .readonly()
                    .list(sortable()))
            .field(ref("orgUnitId", "example.requests.col.org_unit", QueryRef.whole("/iam/org-units", "name"))
                    .column("org_unit_id")
                    .defaultValue(FieldDefault.currentOrgUnit())
                    .list(hidden()))
            .field(instant("modifiedAt", "example.requests.col.modified_at")
                    .system(SystemColumn.MODIFIED_AT)
                    .list(sortable().hidden()))
            .section("main", "entity.section.main", "subject", "productId", "qty", "status")
            .section("decision", "example.requests.section.decision", "resolution", "decidedAt")
            .section("settings", "entity.section.settings", "orgUnitId")
            .actions("create", "update", "delete")
            .workflow(EntityWorkflow.on("status")
                    .state("draft", "example.requests.status.draft")
                    .initial()
                    .state("submitted", "example.requests.status.submitted")
                    .locks("subject", "productId", "qty", "orgUnitId")
                    .state("approved", "example.requests.status.approved")
                    .terminal()
                    .state("rejected", "example.requests.status.rejected")
                    .terminal()
                    .transition("submit", "draft", "submitted")
                    .transition("recall", "submitted", "draft")
                    .transition("approve", "submitted", "approved")
                    .transition("reject", "submitted", "rejected")
                    .confirm("example.requests.reject_confirm")
                    .build())
            .defaultSort("modifiedAt", Entity.Sort.DESC)
            .capabilities(
                    EntityCapability.SAVED_VIEWS,
                    EntityCapability.EXPORT,
                    EntityCapability.HISTORY,
                    EntityCapability.BULK)
            .build();

    /** Named apart from the bean of this configuration class itself. */
    @Bean
    public EntityDefinition exampleRequestsDefinition() {
        return DEFINITION;
    }
}
