set lock_timeout = '2s';
set statement_timeout = '60s';
-- Plan 10/10, item 6.6: the tables of two reference entities of the module example, generated by the cms CLI and
-- finished by hand (docs/cookbook). ex_products is the reference list: a unique code of the live rows, a unit, a price
-- and the archive (ADR-0032, 5.4). ex_requests is the document with statuses: a product of the list, a quantity, the
-- status of its process (draft, submitted, approved, rejected), the decision the approver writes and the moment the
-- hook stamps, and the org unit of its scope (ADR-0013). Names, types and indexes by ADR-0020 and ADR-0032, 14.1;
-- every foreign key has its index.
create table ex_products (
    id bigint generated always as identity constraint ex_products_pkey primary key,
    name text not null constraint ex_products_ck_name check (char_length(name) between 1 and 255),
    code text not null constraint ex_products_ck_code check (code ~ '^[a-z0-9_-]{1,64}$'),
    unit text not null default 'pcs' constraint ex_products_ck_unit check (unit in ('pcs', 'kg', 'l')),
    price_amount numeric(19, 4) constraint ex_products_ck_price_amount check (price_amount >= 0),
    price_currency text constraint ex_products_ck_price_currency check (price_currency in ('UZS', 'USD')),
    attributes jsonb not null default '{}'::jsonb
        constraint ex_products_ck_attributes check (jsonb_typeof(attributes) = 'object'),
    archived_at timestamptz,
    archived_by bigint constraint ex_products_fk_archived_by references md_users (id),
    created_by bigint not null constraint ex_products_fk_created_by references md_users (id),
    modified_by bigint not null constraint ex_products_fk_modified_by references md_users (id),
    created_at timestamptz not null default clock_timestamp(),
    modified_at timestamptz not null default clock_timestamp(),
    revision bigint not null default 1
);

create unique index ex_products_code_uq on ex_products (code) where archived_at is null;
create index ex_products_archived_by_idx on ex_products (archived_by);
create index ex_products_created_by_idx on ex_products (created_by);
create index ex_products_modified_by_idx on ex_products (modified_by);

create table ex_requests (
    id bigint generated always as identity constraint ex_requests_pkey primary key,
    subject text not null constraint ex_requests_ck_subject check (char_length(subject) between 1 and 255),
    product_id bigint not null constraint ex_requests_fk_product references ex_products (id),
    qty numeric(15, 3) not null constraint ex_requests_ck_qty check (qty > 0),
    status text not null default 'draft'
        constraint ex_requests_ck_status check (status in ('draft', 'submitted', 'approved', 'rejected')),
    resolution text constraint ex_requests_ck_resolution check (char_length(resolution) <= 2000),
    decided_at timestamptz,
    org_unit_id bigint constraint ex_requests_fk_org_unit references md_org_units (id),
    attributes jsonb not null default '{}'::jsonb
        constraint ex_requests_ck_attributes check (jsonb_typeof(attributes) = 'object'),
    created_by bigint not null constraint ex_requests_fk_created_by references md_users (id),
    modified_by bigint not null constraint ex_requests_fk_modified_by references md_users (id),
    created_at timestamptz not null default clock_timestamp(),
    modified_at timestamptz not null default clock_timestamp(),
    revision bigint not null default 1
);

create index ex_requests_product_id_idx on ex_requests (product_id);
create index ex_requests_org_unit_id_idx on ex_requests (org_unit_id);
create index ex_requests_created_by_idx on ex_requests (created_by);
create index ex_requests_modified_by_idx on ex_requests (modified_by);
