set lock_timeout = '2s';
set statement_timeout = '60s';
-- Violator of MigrationLintTest: one breach of every rule of ADR-0020.
create table md_lint_probe (
    id bigserial primary key,
    code varchar(20),
    seen_at timestamp,
    updated_at timestamptz,
    constraint lint_probe_code_unique unique (code)
);
create table md_lint_probe_two (id bigint generated by default as identity primary key);
create index idx_lint_probe_code on md_lint_probe (code);
create index security_events_probe_idx on security_events (event_type);
create index concurrently md_lint_probe_seen_idx on md_lint_probe (seen_at);
