-- ============================================================================
-- DWH Platform - Core Instance Initial Seed Data V002
-- ============================================================================

-- 1. Instance Info
insert into md_instance_info (client_code, client_name, resource_profile, license_token, license_status, created_at, modified_at)
values ('DEMO', 'DWH Demo Enterprise', 'M', 'demo_license_token', 'ACTIVE', now(), now())
on conflict (client_code) do nothing;

-- 2. Core Forms
insert into md_forms (code, module, name) values
('iam.profile', 'md', 'Мой профиль'),
('iam.users', 'md', 'Пользователи'),
('rbac.roles', 'md', 'Роли и права'),
('rbac.assignments', 'md', 'Назначение прав'),
('md.custom_fields', 'md', 'Динамические поля'),
('platform.settings', 'md', 'Настройки платформы'),
('tasks.projects', 'ms.task', 'Проекты'),
('tasks.items', 'ms.task', 'Задачи'),
('tasks.comments', 'ms.task', 'Комментарии к задачам'),
('notify.inbox', 'ms.notify', 'Входящие оповещения'),
('notify.preferences', 'ms.notify', 'Настройки уведомлений'),
('platform.announcements', 'ms.notify', 'Объявления')
on conflict (code) do nothing;

-- 3. Core Form Actions
insert into md_form_actions (form_code, action, name) values
('iam.profile', 'view', 'Просмотр профиля'),
('iam.profile', 'update', 'Изменение данных'),
('iam.profile', 'manage_tokens', 'Управление токенами'),
('iam.profile', 'manage_channels', 'Управление каналами'),
('iam.users', 'view', 'Просмотр списка'),
('iam.users', 'create', 'Создание пользователя'),
('iam.users', 'update', 'Редактирование пользователя'),
('iam.users', 'block', 'Блокировка пользователя'),
('iam.users', 'unblock', 'Разблокировка пользователя'),
('rbac.roles', 'view', 'Просмотр ролей'),
('rbac.roles', 'create', 'Создание роли'),
('rbac.roles', 'update', 'Редактирование роли'),
('rbac.roles', 'delete', 'Удаление роли'),
('rbac.roles', 'grant', 'Настройка матрицы прав'),
('md.custom_fields', 'view', 'Просмотр полей'),
('md.custom_fields', 'create', 'Создание поля'),
('md.custom_fields', 'update', 'Редактирование поля'),
('md.custom_fields', 'delete', 'Удаление поля'),
('platform.settings', 'view', 'Просмотр настроек'),
('platform.settings', 'update', 'Изменение настроек'),
('tasks.projects', 'view', 'Просмотр проектов'),
('tasks.projects', 'create', 'Создание проекта'),
('tasks.projects', 'update', 'Редактирование проекта'),
('tasks.items', 'view', 'Просмотр задач'),
('tasks.items', 'create', 'Создание задачи'),
('tasks.items', 'update', 'Редактирование задачи'),
('tasks.comments', 'view', 'Просмотр комментариев'),
('tasks.comments', 'create', 'Добавление комментария'),
('notify.inbox', 'view', 'Просмотр оповещений'),
('platform.announcements', 'view', 'Просмотр объявлений')
on conflict (form_code, action) do nothing;

-- 4. Default Roles
insert into md_roles (name, pcode, state, order_no, created_at, modified_at) values
('Администратор', 'admin', 'A', 10, now(), now()),
('Менеджер', 'manager', 'A', 20, now(), now()),
('Аудитор', 'auditor', 'A', 30, now(), now()),
('Пользователь', 'user', 'A', 40, now(), now())
on conflict (pcode) do nothing;

-- 5. Grant all permissions to admin role
insert into md_role_permissions (role_id, form_code, action)
select r.id, fa.form_code, fa.action
from md_roles r
cross join md_form_actions fa
where r.pcode = 'admin'
on conflict do nothing;

-- 6. Initial Administrator User (login: admin, password: Admin123!)
-- Hash generated by Argon2id (iterations=2, memory=65536, parallelism=2)
insert into md_users (name, login, email, phone, password_hash, state, language, timezone, attributes, is_2fa_enabled, force_password_change, created_at, modified_at)
values ('System Administrator', 'admin', 'admin@dwh.local', '+998901234567',
        '$argon2id$v=19$m=65536,t=2,p=2$0H76KOGIk86/2OFGtHM1bw$UhtQIZZU9UdBBZeaKWeY3CDzzy3bRIPdp6RyivscSzc',
        'A', 'ru', 'Asia/Tashkent', '{}'::jsonb, false, false, now(), now())
on conflict (login) do nothing;

-- 7. Assign admin role to admin user
insert into md_user_roles (user_id, role_id)
select u.id, r.id
from md_users u, md_roles r
where u.login = 'admin' and r.pcode = 'admin'
on conflict do nothing;

-- 8. Materialize effective permissions for admin user
insert into md_effective_permissions (user_id, form_code, action, source_role_id)
select u.id, fa.form_code, fa.action, r.id
from md_users u
join md_user_roles ur on ur.user_id = u.id
join md_roles r on r.id = ur.role_id
join md_role_permissions rp on rp.role_id = r.id
join md_form_actions fa on fa.form_code = rp.form_code and fa.action = rp.action
where u.login = 'admin'
on conflict do nothing;

insert into md_user_permission_versions (user_id, permissions_version, is_recalculating)
select id, 1, false from md_users where login = 'admin'
on conflict do nothing;

-- 9. Task Statuses
insert into ms_task_statuses (pcode, name, color, order_no, is_terminal) values
('new', 'Новая', '#3b82f6', 10, false),
('in_progress', 'В работе', '#eab308', 20, false),
('done', 'Выполнена', '#22c55e', 30, true),
('cancelled', 'Отменена', '#ef4444', 40, true)
on conflict (pcode) do nothing;
