#!/bin/sh
# Writes the runtime part of the edge configuration before nginx starts (ADR-0034, plan 10/10, item 7.4):
#   SMC_WEB_FRAME_SOURCES   - origins the application may embed in frames (embedded reports), separated by
#                             spaces or commas; each is http(s)://host[:port][/path], a leading "*." allowed.
#                             Empty (the default): only the application itself.
#   SMC_WEB_TRUSTED_PROXIES - addresses or CIDR ranges of the proxies in front of this container whose
#                             X-Forwarded-For nginx believes. Empty (the default): the direct peer is the client.
# A value outside these forms stops the container: a header or a trust list is never guessed.
set -eu
# The values are split on whitespace below; "*.host" must never expand to file names.
set -f

runtime_dir="${SMC_WEB_RUNTIME_DIR:-/run/nginx}"
target="$runtime_dir/smc-edge.conf"

fail() {
    echo "40-smc-edge-config: $1" >&2
    exit 1
}

tokens() {
    printf '%s' "$1" | tr ',\t\r\n' '    '
}

frame_sources=""
for source in $(tokens "${SMC_WEB_FRAME_SOURCES:-}"); do
    if ! printf '%s' "$source" | grep -Eq '^https?://(\*\.)?[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(:[0-9]{1,5})?(/[A-Za-z0-9._~/-]*)?$'; then
        fail "SMC_WEB_FRAME_SOURCES: '$source' is not an http(s) origin"
    fi
    frame_sources="$frame_sources $source"
done

real_ip_lines=""
for proxy in $(tokens "${SMC_WEB_TRUSTED_PROXIES:-}"); do
    case "$proxy" in
        0.0.0.0/0 | ::/0) fail "SMC_WEB_TRUSTED_PROXIES: '$proxy' would trust every client" ;;
    esac
    if ! printf '%s' "$proxy" | grep -Eq '^([0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?|[0-9A-Fa-f:]*:[0-9A-Fa-f:]*(/[0-9]{1,3})?)$'; then
        fail "SMC_WEB_TRUSTED_PROXIES: '$proxy' is not an address or a CIDR range"
    fi
    real_ip_lines="${real_ip_lines}set_real_ip_from $proxy;
"
done

mkdir -p "$runtime_dir"
{
    echo "# Generated by 40-smc-edge-config.sh at container start; do not edit."
    echo "map \$host \$smc_frame_sources { default \"$frame_sources\"; }"
    printf '%s' "$real_ip_lines"
    echo "real_ip_header X-Forwarded-For;"
    echo "real_ip_recursive on;"
} > "$target"
echo "40-smc-edge-config: wrote $target"
